### ISSUE TITLE
A question for test set. Please sir, it's important for me.

### ISSUE THREAD

**Issue by hxl835097324** [Xiejiu/second_age_estimation#1]
Does the test set use face alignment? Or resize  the initial images to 224*224 directly.
And is the test set for the comparison methods handled in the same way?

**Comment by JeffersonXie** [comment]
Thanks for your interest in our work. For the images in the test set, before feeding them into the trained network for inference,   all of them are aligned first. This is a common practice for face-based analysis tasks, not limited to age estimation. Regarding your second question, in our comparison with other methods, we adopted the same processing procedures for them.

**Comment by hxl835097324** [comment]
Thank you so much for replying me so quickly.Have a nice day.
